AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates Email Service resources"

Parameters:
  Environment:
    Description: Environment for the frontend like dev, stg or prod
    Type: String
    Default: "dev"
    AllowedValues:
      - prod
      - dev
      - stg
  Application:
    Type: String
    Description: Name of application to prepended to names
    Default: dvix
  Identity:
    Type: String
    Description: Identity for the domain or email
    Default: asifalam0308@gmail.com

Resources:

  # IAM for SES ##########################################

  SESRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SESRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: "sts:AssumeRole"

  SESConfigSet:
    Type: 'AWS::SES::ConfigurationSet'
    Properties:
      Name: !Sub "${Application}-${Environment}-ses-config"
      ReputationOptions:
        ReputationMetricsEnabled: true
      SendingOptions:
        SendingEnabled: true
      SuppressionOptions:
        SuppressedReasons:
          - COMPLAINT
          - BOUNCE

  EmailIdentitySES:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref Identity   # This can be EMAIL or DOMAIN
      DkimAttributes:
        SigningEnabled: true
      ConfigurationSetAttributes: 
        ConfigurationSetName: !Ref SESConfigSet

  EmailIdentityPolicy:
    Type: AWS::SES::IdentityPolicy
    Properties:
      Identity: !Ref EmailIdentitySES
      PolicyName: !Sub "${Application}-${Environment}-ses-identity-policy"
      Roles:
        - !Ref SESRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
              - "ses:SendEmail"
              - "ses:SendRawEmail"
            Resource: "*"
            Principal:
              AWS: "*"